[package]
name = "libsql"
version = "0.1.0"
edition = "2021"
description = "libSQL for Rust"
repository = "https://github.com/libsql/libsql/"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
