name: Makefile CI with bottomless WAL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update submodules
      run: git submodule update --init # not recursive
    
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: configure with bottomless storage
      run: ./configure --enable-bottomless-wal
      
    - name: Run tests
      run: make test

    - name: Run Rust tests
      run: make rusttest
